[package]
name = "edge-php-runtime"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
edge-php-parser = { path = "../parser" }
edge-php-compiler = { path = "../compiler" }
anyhow = { workspace = true }