[package]
name = "edge-php-compiler"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true


[dependencies]
edge-php-parser = { path = "../parser" }
wasm-encoder = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }